### ISSUE TITLE
Util Object?

### ISSUE THREAD

**Issue by nebucaz** [JvSomeren/vue-peerjs#9]
How can we access peer's [util](https://peerjs.com/docs.html#util) object from Vue?
As far as I can see, it's not exported.

**Comment by JvSomeren** [comment]
I believe you are right about that. I found [this issue](https://github.com/peers/peerjs/issues/554#issuecomment-520226613) in the PeerJS repo.

It suggests using `window.peerjs.util` or just `peerjs.util`.

**Comment by nebucaz** [comment]
Thanks for the suggestion, but none of them seem to work. Would it be possible to expose it explicitly in `vue-peer/src/index.js` (sorry, I'm not familiar with creating Vue/NPM Modules, just an idea).

```
export default {
  install(Vue, peer, options) {
    if (!isPeerJS(peer)) {
      throw new Error('[vue-peerjs] you have to pass a 'Peer' instance to the plugin');
    }

    Observe(peer, options);
    // eslint-disable-next-line no-param-reassign
    Vue.prototype.$peer = peer;

--> here 
  }
```

**Comment by JvSomeren** [comment]
This package is just a wrapper around peerjs. So it's unable to import (and thus expose) the util object for the same reasons you are. I'm sorry about that.

**Comment by nebucaz** [comment]
Second try: 
`console.log(window.peerjs.util.browser);`

now seems to work. Thanks
